version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      angular:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
